### ISSUE TITLE
999_outputs error

### ISSUE THREAD

**Issue by tomsherrod** [mrlesmithjr/ansible-elk-pre-processor#1]
Any pointers for elk-preprocessor, config logstash, configuring logstash, 999_outputs failing in the ansible run?
failed: [192.168.5.19] => (item=999_outputs) => {“exit_status”: 1, “failed”: true, “item”: “999_outputs”}
stdout: {:timestamp=>”2015-12-10T15:30:45.230000+0000″, :message=>”Invalid setting for elasticsearch output plugin:\n\n output {\n elasticsearch {\n # This setting must be a path\n # File does not exist or cannot be opened /opt/logstash/lib/logstash/outputs/elasticsearch/elasticsearch-template.json\n template => \”/opt/logstash/lib/logstash/outputs/elasticsearch/elasticsearch-template.json\”\n …\n }\n }”, :level=>:error}
Error: Something is wrong with your configuration.

**Comment by mrlesmithjr** [comment]
Closing this issue as it has tested out successfully in lab
