### ISSUE TITLE
logstash and redis connect issue?

### ISSUE THREAD

**Issue by tomsherrod** [mrlesmithjr/ansible-elk-pre-processor#2]
Hi,
Have you encountered any issues with logstash connecting to redis?
I've used redis-cli from the pre-processors connected to logstashfqdn successfully.
Logstash errors: 
exception=>#<Redis::CannotConnectError: Error connecting to Redis on logstashfqdn:6379 (Errno::ECONNREFUSED)>,
Haproxy says there's a session.
Redis gives no indication.
(multi machine install...not vagrant)
I just don't see an obvious reason of failure.
Any pointers/suggestions?

**Comment by mrlesmithjr** [comment]
What does your 999_outputs.conf look like?

**Comment by tomsherrod** [comment]
It did have the logstashfqdn, I put in the ip.
Even ran bin/logstash /etc/logstash/conf.d/999_outputs.conf --configtest successfully.

# Ansible managed, do not edit directly: /home/ubuntu/ansible-elkstack/roles/ans

ible-elk-pre-processor/templates/etc/logstash/conf.d/999_outputs.conf.j2 by ubun
tu on ansi-admin
#
output {
  if "metric" in [tags] {
    stdout {
      codec => line {
        format => "1m rate: %{documents.rate_1m} ( %{documents.count} )"
      }
    }
  }
}
output {
  redis {
    host => "10.10.10.119"
    data_type => "list"
    key => "logstash"
  }
}

Additional research, the error seems to have stopped. Restart cleared it(?).
Onto the next level. Any debugging tips appreciated.
Information isn't making it to search.

**Comment by mrlesmithjr** [comment]
If the information is not making it into search you need to check your 999_outputs.conf on your elk-processor nodes.

**Comment by tomsherrod** [comment]
Yes sir! Closer.
{:timestamp=>"2016-02-17T23:57:52.928000-0500", :message=>"Error: The setting `host` in plugin `elasticsearch` is obsolete and is no longer available. Please use the 'hosts' setting instead. You can specify multiple entries separated by comma in 'host:port' format. If you have any questions about this, you are invited to visit https://discuss.elastic.co/c/logstash and ask."}
{:timestamp=>"2016-02-17T23:57:52.930000-0500", :message=>"You may be interested in the '--configtest' flag which you can\nuse to validate logstash's configuration before you choose\nto restart a running system."}

I wasn't sure how to modify 999_outputs.conf.j2 without breaking other options. I'm picking up ansible speed, not quite there yet. 
I'm making the change and restarting.

**Comment by mrlesmithjr** [comment]
Ah yes...So did you pull the latest code down from here for the elk-processor role? This was a setting change that was implemented in 2.x of logstash. I had put this in place about a week ago.

**Comment by tomsherrod** [comment]
Yes, I did. 
I'm only using 1 name.
{%   if item.host is defined %}
      host => "{{ item.host }}"
{%   endif %}
{%   if item.hosts is defined %}
      hosts => ["{{ item.hosts }}"]
{%   endif %}

The right place?

**Comment by mrlesmithjr** [comment]
You should not have to mess w/any templates. Just update vars in the role or in group_vars/group_name...
ansible-elk-processor role defaults/main.yml

```
logstash_outputs:
  - output: elasticsearch
    hosts: '{{ logstash_server_fqdn }}:9200'
    protocol: http  #node, transport or http....http is the only protocol supported in 2.x+
    flush_size: 5000
    workers: 2
logstash_server_fqdn: 'logstash.{{ pri_domain_name }}'
pri_domain_name: example.org
```

**Comment by mrlesmithjr** [comment]
Probably the best way to get started is to pull the following repo and follow the info and modify for your environment. This repo will help pull everything together for a deployment of a complete HA ELK-Stack.

https://github.com/mrlesmithjr/ansible-elkstack

**Comment by tomsherrod** [comment]
Yes, that's what I did. I did get it working yesterday. I did have to do a number of tweaks.
I'm pulling a fresh copy today and stepping through again.

Thanks for the assist. Thanks for this project. I've used it to help me understand Ansible!

Tom

**Comment by mrlesmithjr** [comment]
Awesome. Let me know if you run into anything else.
